
package com.fram;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-26T12:19:01.506+03:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "BusinessFaultType", targetNamespace = "http://www.fram.com/User")
public class BusinessException extends Exception {

    private com.fram.BusinessFaultType businessFaultType;

    public BusinessException() {
        super();
    }

    public BusinessException(String message) {
        super(message);
    }

    public BusinessException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BusinessException(String message, com.fram.BusinessFaultType businessFaultType) {
        super(message);
        this.businessFaultType = businessFaultType;
    }

    public BusinessException(String message, com.fram.BusinessFaultType businessFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.businessFaultType = businessFaultType;
    }

    public com.fram.BusinessFaultType getFaultInfo() {
        return this.businessFaultType;
    }
}
