package com.fram;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-26T12:19:01.583+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.fram.com/UserService/", name = "IUserService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IUserService {

    @WebMethod(action = "http://www.fram.com/services/UserService/registerUser")
    @WebResult(name = "UserResponseType", targetNamespace = "http://www.fram.com/User", partName = "parameters")
    public UserResponseType registerUser(

        @WebParam(partName = "parameters", name = "UserRequestType", targetNamespace = "http://www.fram.com/User")
        UserRequestType parameters
    ) throws BusinessException;

    @WebMethod
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "http://www.fram.com/User", partName = "parameters")
    public GetUserDetailsResponse getUserDetails(

        @WebParam(partName = "parameters", name = "getUserDetailsRequest", targetNamespace = "http://www.fram.com/User")
        GetUserDetailsRequest parameters
    );

    @WebMethod
    @WebResult(name = "UsersListResponseType", targetNamespace = "http://www.fram.com/User", partName = "parameters")
    public UsersListResponseType getAllUsers()
;
}
